# Generated by Django 3.1.6 on 2021-02-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
                ('country', models.CharField(choices=[('IND', 'India'), ('UAE', 'Uae'), ('CA', 'Canada')], max_length=3)),
                ('city', models.CharField(max_length=20)),
                ('postalcode', models.CharField(max_length=20)),
            ],
        ),
    ]
