# Generated by Django 3.1.6 on 2021-03-24 15:21

import chatbot.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=255, null=True, unique=True)),
                ('telegram_status', models.BooleanField(default=False)),
                ('telegram_key', models.CharField(max_length=255, null=True, unique=True)),
                ('data_url', models.URLField(max_length=255, null=True)),
                ('data_key', models.CharField(max_length=255, null=True)),
                ('messages', models.JSONField(default=chatbot.core.models.default_messages)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.JSONField(default=list)),
                ('intent_model', models.BinaryField(null=True)),
                ('ner_model', models.BinaryField(null=True)),
                ('chatbot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.chatbot')),
            ],
        ),
    ]
