# Generated by Django 3.1.6 on 2021-04-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='facebook',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='facebook_key',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='facebook_status',
            field=models.BooleanField(default=False),
        ),
    ]
