# Generated by Django 3.1.6 on 2021-03-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210312_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='data_url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
