# Generated by Django 3.1.6 on 2021-03-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210312_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='intent_model',
            field=models.BinaryField(null=True),
        ),
    ]
