# Generated by Django 3.2.2 on 2021-05-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='whatsapp',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='whatsapp_key',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='whatsapp_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='auth',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='training',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
