# Generated by Django 3.2.4 on 2021-06-26 12:08

import convobot.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=255, null=True, unique=True)),
                ('telegram_status', models.BooleanField(default=False)),
                ('telegram_key', models.CharField(max_length=255, null=True, unique=True)),
                ('messenger_status', models.BooleanField(default=False)),
                ('messenger_key', models.CharField(max_length=255, null=True, unique=True)),
                ('whatsapp_status', models.BooleanField(default=False)),
                ('whatsapp_key', models.CharField(max_length=255, null=True, unique=True)),
                ('data_url', models.URLField(max_length=255, null=True)),
                ('data_key', models.CharField(max_length=255, null=True)),
                ('messages', models.JSONField(default=convobot.models.default_messages)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LTS',
            fields=[
                ('chatbot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='LTS', serialize=False, to='convobot.chatbot')),
                ('botsign', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.CharField(max_length=255, null=True)),
                ('url', models.URLField(null=True)),
                ('training_status', models.PositiveSmallIntegerField(null=True)),
                ('dataset', models.JSONField(default=list)),
                ('validation_token', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('uname', models.CharField(max_length=255, null=True)),
                ('telegram', models.PositiveIntegerField(null=True)),
                ('messenger', models.PositiveIntegerField(null=True)),
                ('whatsapp', models.PositiveIntegerField(null=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth', to='convobot.chatbot')),
            ],
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveSmallIntegerField()),
                ('channel', models.CharField(max_length=100)),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='convobot.chatbot')),
            ],
        ),
    ]
