# Generated by Django 3.2.4 on 2021-06-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convobot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lts',
            name='dataset_ok',
            field=models.BooleanField(blank=True, default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='lts',
            name='dataset',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='lts',
            name='training_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lts',
            name='validation_token',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
